name: CI

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  push:
    branches:
      - pre
  pull_request:
    branches: 
      - pre

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/office/Office
            azure-pipeline-name: '1JS Upgrade Checker'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
